#!/usr/bin/env python3
"""高ポリゴン・テストシーン用の OBJ（と Mitsuba XML）を生成する。

生成される 3 つのメッシュは、BVH に対して性質の異なる負荷を与える:

- ``hp_knot.obj``     トーラス結び目のチューブ。三角形が密で大きさが揃い、
                      空間的には細長い曲線に沿って分布する。
- ``hp_terrain.obj``  変位付きの地形グリッド。薄く広がり、斜面で細長い三角形が混ざる。
- ``hp_blob.obj``     中規模の UV 球。XML から多数インスタンス化され、
                      インスタンス経由の経路と world_bounds 事前棄却を働かせる。

OBJ はリポジトリにコミットしない（100 万三角形で 100MB 超）。既定の出力先
``assets/highpoly/`` は ``.gitignore`` の ``*.obj`` で無視される。``sample/`` は
``!sample/**`` で無視が打ち消されるので、そこには置かないこと。

使い方:

    python3 tools/gen_highpoly.py                      # 既定 100 万三角形
    python3 tools/gen_highpoly.py --tris 5000000       # 500 万三角形
    python3 tools/gen_highpoly.py --tris 100000 \
        --outdir /tmp/hp --scene-out /tmp/hp/scene.xml # 別preset を別の場所に

``--tris`` は「シーン全体の三角形数」で、インスタンスぶんを展開した数え方
（blob は 1 メッシュを ``--instances`` 個ぶん数える）。内訳は結び目 40% /
地形 40% / インスタンス群 20%。
"""

import argparse
import math
import os

# ---------------------------------------------------------------- OBJ writing

def write_obj(path, verts, faces, normals=None):
    """頂点・面（0-based インデックスの三つ組）・任意で頂点法線を OBJ で書き出す。

    法線を渡した場合は頂点と 1:1 に対応させ、面は ``f v//vn`` 形式で書く
    （スムーズシェーディングの検証用。tinypt は `vn` を読んで補間する）。
    """
    with open(path, "w", buffering=1 << 20) as f:
        f.write("# generated by tools/gen_highpoly.py -- do not commit\n")
        out = []

        def flush(force=False):
            if out and (force or len(out) >= 65536):
                f.write("\n".join(out) + "\n")
                del out[:]

        for x, y, z in verts:
            out.append("v %.6f %.6f %.6f" % (x, y, z))
            flush()
        flush(True)
        if normals:
            for x, y, z in normals:
                out.append("vn %.6f %.6f %.6f" % (x, y, z))
                flush()
            flush(True)
        for a, b, c in faces:
            if normals:
                out.append("f %d//%d %d//%d %d//%d" % (a + 1, a + 1, b + 1, b + 1, c + 1, c + 1))
            else:
                out.append("f %d %d %d" % (a + 1, b + 1, c + 1))
            flush()
        flush(True)
    return len(verts), len(faces)


# ---------------------------------------------------------------- generators

def torus_knot(ring_segments, tube_segments, scale=0.42, tube_radius=0.16, p=2, q=3):
    """(p,q) トーラス結び目に沿ったチューブ。三角形が密で大きさが揃うメッシュ。

    フレームは Frenet（接線・主法線）で、周期的なので継ぎ目に隙間ができない。
    """
    def curve(t):
        r = 2.0 + math.cos(q * t)
        return (r * math.cos(p * t) * scale,
                -math.sin(q * t) * scale,
                r * math.sin(p * t) * scale)

    verts = []
    norms = []
    two_pi = 2.0 * math.pi
    h = two_pi / (ring_segments * 64.0)
    for i in range(ring_segments):
        t = two_pi * i / ring_segments
        c = curve(t)
        cp = curve(t + h)
        cm = curve(t - h)
        # 一階微分（接線）と二階微分から Frenet フレームを作る
        tx, ty, tz = (cp[0] - cm[0], cp[1] - cm[1], cp[2] - cm[2])
        tl = math.sqrt(tx * tx + ty * ty + tz * tz) or 1.0
        tx, ty, tz = tx / tl, ty / tl, tz / tl
        dx, dy, dz = (cp[0] - 2 * c[0] + cm[0], cp[1] - 2 * c[1] + cm[1], cp[2] - 2 * c[2] + cm[2])
        # 接線成分を落として主法線に
        d = dx * tx + dy * ty + dz * tz
        nx, ny, nz = dx - d * tx, dy - d * ty, dz - d * tz
        nl = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
        nx, ny, nz = nx / nl, ny / nl, nz / nl
        bx, by, bz = ty * nz - tz * ny, tz * nx - tx * nz, tx * ny - ty * nx
        for j in range(tube_segments):
            a = two_pi * j / tube_segments
            ca, sa = math.cos(a), math.sin(a)
            # チューブの法線は中心曲線から外向きの半径方向（解析的に求まる）
            rx, ry, rz = ca * nx + sa * bx, ca * ny + sa * by, ca * nz + sa * bz
            verts.append((c[0] + tube_radius * rx, c[1] + tube_radius * ry, c[2] + tube_radius * rz))
            norms.append((rx, ry, rz))

    faces = []
    for i in range(ring_segments):
        i1 = (i + 1) % ring_segments
        for j in range(tube_segments):
            j1 = (j + 1) % tube_segments
            a = i * tube_segments + j
            b = i * tube_segments + j1
            c = i1 * tube_segments + j1
            d = i1 * tube_segments + j
            faces.append((a, b, c))
            faces.append((a, c, d))
    return verts, faces, norms


def terrain(n, half_extent=8.0, amplitude=0.35):
    """変位付きの地形グリッド（n x n 四角形 = 2n² 三角形）。

    薄く広がり、斜面では細長い三角形が混ざる。変位は正弦の和（決定的・依存なし）。
    """
    verts = []
    norms = []
    step = 2.0 * half_extent / n
    for iz in range(n + 1):
        z = -half_extent + step * iz
        for ix in range(n + 1):
            x = -half_extent + step * ix
            y = (amplitude * math.sin(0.9 * x) * math.cos(0.7 * z)
                 + 0.45 * amplitude * math.sin(2.3 * x + 1.7 * z)
                 + 0.20 * amplitude * math.sin(5.1 * z - 0.6 * x))
            verts.append((x, y, z))
            # 高さ場 y(x,z) の解析的な勾配から法線 (-dy/dx, 1, -dy/dz) を作る
            dydx = (amplitude * 0.9 * math.cos(0.9 * x) * math.cos(0.7 * z)
                    + 0.45 * amplitude * 2.3 * math.cos(2.3 * x + 1.7 * z)
                    + 0.20 * amplitude * -0.6 * math.cos(5.1 * z - 0.6 * x))
            dydz = (amplitude * math.sin(0.9 * x) * -0.7 * math.sin(0.7 * z)
                    + 0.45 * amplitude * 1.7 * math.cos(2.3 * x + 1.7 * z)
                    + 0.20 * amplitude * 5.1 * math.cos(5.1 * z - 0.6 * x))
            nl = math.sqrt(dydx * dydx + 1.0 + dydz * dydz)
            norms.append((-dydx / nl, 1.0 / nl, -dydz / nl))
    faces = []
    w = n + 1
    for iz in range(n):
        for ix in range(n):
            a = iz * w + ix
            b = a + 1
            c = a + w + 1
            d = a + w
            faces.append((a, b, c))
            faces.append((a, c, d))
    return verts, faces, norms


def uv_sphere(nu, nv, radius=1.0):
    """UV 球（極は三角形、それ以外は四角形を 2 分割）。インスタンス用の中規模メッシュ。"""
    verts = [(0.0, radius, 0.0)]
    for iv in range(1, nv):
        theta = math.pi * iv / nv
        st, ct = math.sin(theta), math.cos(theta)
        for iu in range(nu):
            phi = 2.0 * math.pi * iu / nu
            verts.append((radius * st * math.cos(phi), radius * ct, radius * st * math.sin(phi)))
    verts.append((0.0, -radius, 0.0))
    south = len(verts) - 1

    def ring(iv, iu):  # iv in 1..nv-1
        return 1 + (iv - 1) * nu + (iu % nu)

    faces = []
    for iu in range(nu):
        faces.append((0, ring(1, iu + 1), ring(1, iu)))
    for iv in range(1, nv - 1):
        for iu in range(nu):
            a, b = ring(iv, iu), ring(iv, iu + 1)
            c, d = ring(iv + 1, iu + 1), ring(iv + 1, iu)
            faces.append((a, b, c))
            faces.append((a, c, d))
    for iu in range(nu):
        faces.append((south, ring(nv - 1, iu), ring(nv - 1, iu + 1)))
    # 球の法線は中心からの単位ベクトル（= 頂点位置 / 半径）
    norms = [(x / radius, y / radius, z / radius) for (x, y, z) in verts]
    return verts, faces, norms


# ---------------------------------------------------------------- scene XML

INSTANCE_BSDFS = [
    '<bsdf type="diffuse"><srgb name="reflectance" value="0.80, 0.35, 0.28"/></bsdf>',
    '<bsdf type="roughconductor">'
    '<string name="distribution" value="ggx"/><float name="alpha" value="0.12"/>'
    '<srgb name="specular_reflectance" value="0.92, 0.90, 0.88"/></bsdf>',
    '<bsdf type="dielectric"><float name="int_ior" value="1.5"/></bsdf>',
    '<bsdf type="diffuse"><srgb name="reflectance" value="0.35, 0.55, 0.80"/></bsdf>',
]


def scene_xml(rel_dir, grid, tri_total, per_mesh):
    """既定プリセットのシーン XML を組み立てる（インスタンス配置はここが唯一の定義）。"""
    def obj_path(name):
        return "%s/%s" % (rel_dir, name) if rel_dir else name

    lines = []
    a = lines.append
    a('<?xml version="1.0" encoding="utf-8"?>')
    a('<!-- 高ポリゴン・テストシーン（読み込み / BVH 構築 / 描画の性能確認用）。')
    a('')
    a('     OBJ はリポジトリに入っていない。先に生成すること:')
    a('         python3 tools/gen_highpoly.py            # 既定 約 %d 三角形' % tri_total)
    a('         python3 tools/gen_highpoly.py --tris 5000000')
    a('     生成物はこの XML から見て %s/ に置かれる（.gitignore の *.obj で無視される）。' % (rel_dir or "."))
    a('     OBJ が無いと各 shape が "failed to load obj ...; skipped" と警告され、')
    a('     そのメッシュ抜きで描画が続く点に注意（全 OBJ が欠けても真っ黒にはならず、環境光だけの一様な青灰色のフレームになる）。')
    a('')
    a('     構成: トーラス結び目のチューブ（密で均一な三角形）+ 変位地形（薄く広い、')
    a('     細長い三角形混じり）+ 中規模メッシュ %d インスタンス（diffuse /' % (grid * grid))
    a('     roughconductor / dielectric）+ 天井の面光源 + 弱い constant 環境光。')
    a('')
    a('     使い方: tinypt --scene sample/highpoly.xml --spp 16 -o renders/highpoly.ppm -->')
    a('<scene version="3.0.0">')
    a('  <integrator type="path">')
    a('    <integer name="max_depth" value="12"/>')
    a('    <integer name="rr_depth" value="5"/>')
    a('  </integrator>')
    a('  <sampler type="independent"><integer name="sample_count" value="16"/></sampler>')
    a('  <film type="hdrfilm">')
    a('    <integer name="width" value="800"/>')
    a('    <integer name="height" value="600"/>')
    a('  </film>')
    a('')
    a('  <sensor type="perspective">')
    a('    <float name="fov" value="42"/>')
    a('    <string name="fov_axis" value="y"/>')
    a('    <transform name="to_world">')
    a('      <lookat origin="0, 4.4, 10.5" target="0, 1.0, -1.0" up="0, 1, 0"/>')
    a('    </transform>')
    a('  </sensor>')
    a('')
    a('  <!-- 変位地形（薄く広がるメッシュ） -->')
    a('  <shape type="obj">')
    a('    <string name="filename" value="%s"/>' % obj_path("hp_terrain.obj"))
    a('    <bsdf type="diffuse"><srgb name="reflectance" value="0.42, 0.45, 0.40"/></bsdf>')
    a('  </shape>')
    a('')
    a('  <!-- トーラス結び目のチューブ（密で大きさの揃った三角形） -->')
    a('  <shape type="obj">')
    a('    <string name="filename" value="%s"/>' % obj_path("hp_knot.obj"))
    a('    <transform name="to_world">')
    a('      <translate x="0" y="2.3" z="0"/>')
    a('      <rotate x="1" y="0" z="0" angle="-20"/>')
    a('      <scale value="1.35"/>')
    a('    </transform>')
    a('    <bsdf type="roughconductor">')
    a('      <string name="distribution" value="ggx"/>')
    a('      <float name="alpha" value="0.14"/>')
    a('      <srgb name="specular_reflectance" value="0.95, 0.80, 0.42"/>')
    a('    </bsdf>')
    a('  </shape>')
    a('')
    a('  <!-- 中規模メッシュ（%d 三角形）の %dx%d インスタンス。tinypt は shape ごとに' % (per_mesh, grid, grid))
    a('       OBJ を読み直して Mesh を作るので、ここは読み込みと BVH 構築の負荷でもある。 -->')
    span = 5.6
    for iz in range(grid):
        for ix in range(grid):
            x = -span + 2.0 * span * ix / (grid - 1) if grid > 1 else 0.0
            z = -span + 2.0 * span * iz / (grid - 1) if grid > 1 else 0.0
            k = (ix + 2 * iz) % len(INSTANCE_BSDFS)
            s = 0.34 + 0.10 * ((ix * 7 + iz * 3) % 5) / 4.0
            ang = (ix * 37 + iz * 53) % 360
            a('  <shape type="obj">')
            a('    <string name="filename" value="%s"/>' % obj_path("hp_blob.obj"))
            a('    <transform name="to_world">')
            a('      <translate x="%.3f" y="%.3f" z="%.3f"/>' % (x, 0.34 + 0.5 * s, z))
            a('      <rotate x="0" y="1" z="0" angle="%d"/>' % ang)
            a('      <scale value="%.3f"/>' % s)
            a('    </transform>')
            a('    %s' % INSTANCE_BSDFS[k])
            a('  </shape>')
    a('')
    a('  <!-- 天井の面光源（下向き） -->')
    a('  <shape type="rectangle">')
    a('    <transform name="to_world">')
    a('      <translate x="0" y="7.0" z="1.5"/><rotate x="1" angle="90"/><scale value="2.2"/>')
    a('    </transform>')
    a('    <emitter type="area"><rgb name="radiance" value="7.5, 7.0, 6.2"/></emitter>')
    a('  </shape>')
    a('')
    a('  <!-- 弱い環境光（env NEE / MIS も通す） -->')
    a('  <emitter type="constant"><rgb name="radiance" value="0.05, 0.08, 0.13"/></emitter>')
    a('</scene>')
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description="高ポリゴン・テストシーンの OBJ を生成する")
    ap.add_argument("--tris", type=int, default=1_000_000,
                    help="シーン全体の目標三角形数（インスタンス展開後、既定 1000000）")
    ap.add_argument("--instances", type=int, default=36,
                    help="blob のインスタンス数。sample/highpoly.xml は 36（6x6）(既定 36)")
    ap.add_argument("--outdir", default="assets/highpoly", help="OBJ の出力先（既定 assets/highpoly）")
    ap.add_argument("--no-normals", action="store_true",
                    help="頂点法線 (vn) を書かない（面法線だけの比較用。既定は書く）")
    ap.add_argument("--scene-out", default=None,
                    help="シーン XML も書き出す場合の出力先（省略時は書き出さない）")
    args = ap.parse_args()

    if args.tris < 1000:
        ap.error("--tris は 1000 以上にすること")
    grid = max(1, int(round(math.sqrt(args.instances))))
    n_inst = grid * grid

    budget_knot = int(args.tris * 0.40)
    budget_terrain = int(args.tris * 0.40)
    budget_blob = max(1, args.tris - budget_knot - budget_terrain)

    # 結び目: 2·R·S 三角形。チューブ方向と周方向の比を 16:1 にする。
    rs = max(64, budget_knot // 2)
    tube_segments = max(8, int(round(math.sqrt(rs / 16.0))))
    ring_segments = max(16, rs // tube_segments)
    # 地形: 2·n² 三角形
    n_grid = max(4, int(round(math.sqrt(budget_terrain / 2.0))))
    # blob: 1 インスタンスあたりの三角形数から UV 球の分割数を決める（2·nu·nv - 2·nu ≈ nu²）
    per_inst = max(32, budget_blob // n_inst)
    nu = max(6, int(round(math.sqrt(per_inst))))
    nv = max(3, nu // 2)

    os.makedirs(args.outdir, exist_ok=True)
    report = []
    for name, (verts, faces, norms) in (
        ("hp_knot.obj", torus_knot(ring_segments, tube_segments)),
        ("hp_terrain.obj", terrain(n_grid)),
        ("hp_blob.obj", uv_sphere(nu, nv)),
    ):
        path = os.path.join(args.outdir, name)
        nv_, nf_ = write_obj(path, verts, faces, None if args.no_normals else norms)
        size = os.path.getsize(path)
        report.append((name, nv_, nf_, size))
        print("%-16s verts=%-9d tris=%-9d %6.1f MB  %s" % (name, nv_, nf_, size / 1e6, path))

    blob_tris = report[2][2]
    total = report[0][2] + report[1][2] + blob_tris * n_inst
    print("scene total: %d triangles (blob %d x %d instances)" % (total, blob_tris, n_inst))

    if args.scene_out:
        scene_dir = os.path.dirname(os.path.abspath(args.scene_out)) or "."
        rel = os.path.relpath(os.path.abspath(args.outdir), scene_dir)
        with open(args.scene_out, "w") as f:
            f.write(scene_xml(rel.replace(os.sep, "/"), grid, total, blob_tris))
        print("scene xml:   %s" % args.scene_out)


if __name__ == "__main__":
    main()
